### ISSUE TITLE
Editor eroare -  'ascii' codec can't decode byte 0xc4 in position 15: ordinal not in range(128) 

### ISSUE THREAD

**Issue by baditaflorin** [cristianbogdan/road-coloring#1]
S-ar putea sa fie din cauza ca est vorba de numele Vodă, cu diacritice.

Am primit acesta eroare cand am dat salveaza la OSM, dupa ce am selectat tipul d calitate a drumului

Selectate: 1 Strada Cuza Vodă:1    ultimul selectat (Strada Cuza Vodă)
Calitatea (smoothness): excellent  good  intermediate  bad  very_bad  horrible  very_horrible  impassable  
Detalii (surface_survey)  
2016MAR_
Comentarii OSM  
Strada Cuza Voda smoothness
 Salvare la OSM!    'ascii' codec can't decode byte 0xc4 in position 15: ordinal not in range(128)

'ascii' codec can't decode byte 0xc4 in position 15: ordinal not in range(128)

**Comment by baditaflorin** [comment]
Da, vad ca daca am sters din comentariu caracterul cu diacritice, a mers http://www.openstreetmap.org/changeset/38132262

Deci ar trebui sa faca o filtrare mai buna, sau sa renunt automat la diacritice daca nu poate sa fie convertit utf 8 sau ceva

**Comment by strainu** [comment]
Lipsește un .decode('utf8') probabil
